#runningInformationDatabase:
#  image: mysql
#  ports:
#    - "3306:3306"
#  environment:
#    - MYSQL_ROOT_PASSWORD=root

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "runningInfoAnalysis_db"
  ports:
    - "3306:3306"