server:
  port: 8090
spring:
  application:
    name: homework1
  datasource:
    url: jdbc:mysql://localhost:3306/runningInfoAnalysis_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update